name: Android CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'

      # Android SDK + cmdline-tools en el runner
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install SDK packages
        run: sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      # Compila con Gradle 8.7 SIN wrapper
      - name: Build Debug APK
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.7
          arguments: assembleDebug

      - name: Upload Debug APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ObsiModules-debug-apk
          path: app/build/outputs/apk/debug/*.apk

  # Opcional: release manual firmado (requiere secretos). 
  # Si aún no firmas, puedes omitir este job completo.
  release:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install SDK packages
        run: sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      - name: Decode keystore
        run: |
          mkdir -p $HOME/keystore
          echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" | base64 -d > $HOME/keystore/obsimod.jks

      - name: Create signing properties
        run: |
          cat << 'EOF' > signing.properties
          storeFile=$HOME/keystore/obsimod.jks
          storePassword=${{ secrets.SIGNING_STORE_PASSWORD }}
          keyAlias=${{ secrets.SIGNING_KEY_ALIAS }}
          keyPassword=${{ secrets.SIGNING_KEY_PASSWORD }}
          EOF

      - name: Build Release APK (signed)
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.7
          arguments: assembleRelease -PsigningPropsFile=signing.properties

      - name: Upload Release APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ObsiModules-release-apk
          path: app/build/outputs/apk/release/*.apk
