name: Android CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew clean assembleDebug

      - name: Upload Debug APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ObsiModules-debug-apk
          path: app/build/outputs/apk/debug/*.apk

  release:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'

      - name: Decode keystore
        run: |
          mkdir -p $HOME/keystore
          echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" | base64 -d > $HOME/keystore/obsimod.jks

      - name: Create signing properties
        run: |
          cat << 'EOF' > signing.properties
          storeFile=$HOME/keystore/obsimod.jks
          storePassword=${{ secrets.SIGNING_STORE_PASSWORD }}
          keyAlias=${{ secrets.SIGNING_KEY_ALIAS }}
          keyPassword=${{ secrets.SIGNING_KEY_PASSWORD }}
          EOF

      - name: Build Release APK (signed)
        run: ./gradlew clean assembleRelease -PsigningPropsFile=signing.properties

      - name: Upload Release APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ObsiModules-release-apk
          path: app/build/outputs/apk/release/*.apk
